nats-ballerina/src/nats/tests/nats_basic_server_tests.bal, nats-native/build.gradle, nats-native/src/main/java/org/ballerinalang/nats/Constants.java
$title
Fixes: https://github.com/ballerina-platform/module-ballerinax-nats/issues/2
=> Add tests for the basic server

build.gradle, nats-ballerina/src/nats/tests/nats_basic_server_tests.bal
=> Update for slp3

nats-ballerina/build.gradle
=> Enable skip tests parameter

nats-ballerina/Ballerina.toml
=> Parameterize Ballerina.toml versions

.github/workflows/build-master.yml, README.md, nats-ballerina/build.gradle, nats-ballerina/src/nats/connection/connection.bal, nats-ballerina/src/nats/streaming/listener.bal, nats-ballerina/src/nats/streaming/producer.bal
=> Update NATS module

nats-ballerina/src/nats/basic/message.bal, nats-ballerina/src/nats/basic/producer.bal, nats-ballerina/src/nats/basic/subscriber.bal, nats-ballerina/src/nats/connection/connection.bal, nats-ballerina/src/nats/streaming/listener.bal, nats-ballerina/src/nats/streaming/message.bal, nats-ballerina/src/nats/streaming/producer.bal
=> Fix module with object syntax change

nats-native/src/main/java/org/ballerinalang/nats/Constants.java, nats-native/src/main/java/org/ballerinalang/nats/Utils.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/GracefulStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ImmediateStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/Request.java, nats-native/src/main/java/org/ballerinalang/nats/connection/Close.java, nats-native/src/main/java/org/ballerinalang/nats/connection/Init.java, nats-native/src/main/java/org/ballerinalang/nats/connection/NatsStreamingConnection.java, nats-native/src/main/java/org/ballerinalang/nats/observability/NatsTracingUtil.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/BallerinaNatsStreamingConnectionFactory.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Close.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/StreamingListener.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Subscribe.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/message/Ack.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/AckListener.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Close.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Publish.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml, nats-ballerina/src/nats/basic/message.bal, nats-ballerina/src/nats/basic/producer.bal, nats-ballerina/src/nats/basic/subscriber.bal, nats-ballerina/src/nats/commons.bal, nats-ballerina/src/nats/connection/connection.bal, nats-ballerina/src/nats/error.bal, nats-ballerina/src/nats/streaming/listener.bal, nats-ballerina/src/nats/streaming/message.bal, nats-ballerina/src/nats/streaming/producer.bal
=> Update module with Isolated change

nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/AckListener.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Publish.java
Remove deprecated API
Replace deprecated API NonBlockingCallback with BalEnv param for interop
API deprecated in - ballerina-platform/ballerina-lang#25787
Duplicate change prior to stdlib move - ballerina-platform/ballerina-lang#25854
=> Migrate NonBlockingCallback to BalEnv

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md, build.gradle, nats-ballerina/build.gradle
=> Add GitHub release workflow

gradle.properties, nats-native/src/main/java/org/ballerinalang/nats/Constants.java
=> Bump developement version

nats-native/src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin
=> Remove compiler plugin from resources

build.gradle, gradle.properties, nats-native/build.gradle
=> Remove langlib dependencies

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, nats-native/build.gradle, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Subscribe.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/AckListener.java, spotbugs-exclude.xml
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/235
$title
=> Add checkstyle check

nats-native/src/main/java/org/ballerinalang/nats/Constants.java, nats-native/src/main/java/org/ballerinalang/nats/Utils.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/GracefulStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ImmediateStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/CloseConnection.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/Publish.java, nats-native/src/main/java/org/ballerinalang/nats/basic/producer/Request.java, nats-native/src/main/java/org/ballerinalang/nats/connection/Init.java, nats-native/src/main/java/org/ballerinalang/nats/connection/NatsStreamingConnection.java, nats-native/src/main/java/org/ballerinalang/nats/observability/NatsTracingUtil.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/BallerinaNatsStreamingConnectionFactory.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Attach.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Close.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/StreamingListener.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/consumer/Subscribe.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/AckListener.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Close.java, nats-native/src/main/java/org/ballerinalang/nats/streaming/producer/Publish.java
=> Migrate ballerina runtime APIs

nats-ballerina/build.gradle
=> Enable doc generation and caches

build.gradle, gradle.properties, nats-ballerina/Ballerina.toml, nats-ballerina/build.gradle
=> Remove transitive dependencies

build.gradle, gradle.properties
=> Remove stringutils test transitive dependency

nats-native/src/main/java/org/ballerinalang/nats/observability/NatsTracingUtil.java
=> Fix traceResourceInvocation function logic

.github/workflows/publish-release.yml
=> Fix setting env in publish-release.yml

gradle.properties
=> Update dependencies for slp7

nats-ballerina/tests/nats_basic_server_tests.bal, nats-ballerina/types.bal
=> Add service annotation support

nats-ballerina/tests/nats_basic_server_tests.bal
=> Fix log api in test

nats-ballerina/build.gradle
Fix tests not running in build master workflow
https://github.com/ballerina-platform/ballerina-standard-library/issues/767
=> Fix tests not running in build master workflow

gradle.properties
=> Bump dependencies to snapshot version

nats-ballerina/init.bal, nats-native/src/main/java/org/ballerinalang/nats/Constants.java, nats-native/src/main/java/org/ballerinalang/nats/Utils.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Request.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ErrorHandler.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java
$title
https://github.com/ballerina-platform/ballerina-standard-library/issues/788
=> Remove hard coded ballerina version in java code

build.gradle, gradle.properties, nats-ballerina/Ballerina.toml, nats-ballerina/build.gradle, nats-ballerina/tests/nats_basic_server_tests.bal
=> Migrate runtime:sleep to lang.runtime:sleep

nats-ballerina/tests/nats_basic_server_tests.bal
=> Update module with changes in testerina

nats-ballerina/records.bal
Make auth related configuration fields mandatory in their respective config records.
=> Fix mandating auth related configurations

nats-ballerina/build.gradle
Update ballerina command to bal command
issue https://github.com/ballerina-platform/ballerina-lang/issues/27680
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR …
=> Update ballerina command to bal command

nats-ballerina/client.bal, nats-ballerina/init.bal, nats-ballerina/listener.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

nats-ballerina/Ballerina.toml, nats-ballerina/Dependencies.toml, nats-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

nats-ballerina/build.gradle
=> Revert Dependency toml file after build

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, nats-ballerina/build.gradle
=> Enable code coverage report publication

nats-ballerina/build.gradle
=> Avoid running tests when publishing

nats-ballerina/build.gradle
$title
https://github.com/ballerina-platform/ballerina-standard-library/issues/899
=> Enable publishing to Ballerina Central

.github/workflows/publish-release.yml, build.gradle, gradle.properties, nats-ballerina/build.gradle
=> Update module version

nats-ballerina/build.gradle
=> Throw exception when central token not present

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, nats-ballerina/build.gradle, nats-ballerina/client.bal, nats-ballerina/error.bal, nats-ballerina/listener.bal, nats-ballerina/records.bal, nats-native/src/main/java/org/ballerinalang/nats/Constants.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Init.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/connection/ConnectionUtils.java
https://github.com/ballerina-platform/ballerina-standard-library/issues/1044
=> Add changes from API review 

nats-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

nats-ballerina/client.bal, nats-ballerina/listener.bal, nats-ballerina/records.bal, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Init.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Init.java, nats-native/src/main/java/org/ballerinalang/nats/connection/ConnectionUtils.java
Move the `url` field in to the `ConnectionConfig` record.
=> Add connection url as a field in connection config

gradle.properties, nats-ballerina/tests/nats_basic_server_tests.bal
=> Update log api usages with latest changes

nats-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

nats-ballerina/client.bal, nats-ballerina/listener.bal, nats-ballerina/records.bal
=> Rename ConnectionConfig to ConnectionConfiguration

build.gradle, nats-ballerina/build.gradle
=> Strip stdlib dependency version

.github/workflows/central-publish.yml, README.md, nats-ballerina/build.gradle
Incorporate all tests, build, and push into one task.
Related to ballerina-platform/ballerina-standard-library#1247
=> Move Ballerina Build, Test and publishing to a single task

nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/DefaultMessageHandler.java
=> Fix passing return type args to invokeMethodAsync

nats-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, nats-ballerina/build.gradle
Standardize build script of Ballerina module
Fixes:
=> Apply Gradle Ballerina plugin for Ballerina module build

nats-ballerina/client.bal, nats-ballerina/listener.bal, nats-native/src/main/java/org/ballerinalang/nats/Constants.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/CloseConnection.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Init.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Publish.java, nats-native/src/main/java/org/ballerinalang/nats/basic/client/Request.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Detach.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/GracefulStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/ImmediateStop.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Register.java, nats-native/src/main/java/org/ballerinalang/nats/basic/consumer/Start.java
$title
1. init functions of client and listener
2. start function in listener -> ballerina function returns error? java function doesn't return anything. return type mismatch
=> Move extern functions inside the classes

README.md, nats-ballerina/Module.md, nats-ballerina/Package.md, nats-ballerina/client.bal, nats-ballerina/listener.bal, nats-ballerina/records.bal
Remarks
https://github.com/ballerina-platform/ballerina-standard-library/issues/1379
=> Improve the API documentation and markdown files

nats-ballerina/build.gradle
Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'
=> Update flag for coverage format

nats-ballerina/client.bal, nats-ballerina/listener.bal
=> Make nats:client class isolated

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle, nats-ballerina/Package.md
$title
Remarks
ballerina-platform/ballerina-release#547 
ballerina-platform/ballerina-standard-library#1462
=> Update Package.md and workflow configs

codecov.yml
$title
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1660
=> Add CodeCoverage target for package

.github/workflows/daily-build.yml
Add daily build
Fixes: https://github.com/ballerina-platform/ballerina-release/issues/1192
=> Add daily build with failure notification

ballerina/Dependencies.toml, ballerina/tests/nats_basic_server_tests.bal, native/src/main/java/io/ballerina/stdlib/nats/Constants.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/Detach.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/Register.java
Related to: ballerina-platform/ballerina-standard-library#2040
=> Remove listener logs

ballerina/types.bal, changelog.md, gradle.properties
related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398
=> Mark NATS service-type distinct

ballerina/client.bal, ballerina/records.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/tls_connection_tests.bal, ballerina/types.bal, native/src/main/java/io/ballerina/stdlib/nats/Constants.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java, native/src/main/java/io/ballerina/stdlib/nats/observability/NatsObservabilityConstants.java, native/src/main/java/io/ballerina/stdlib/nats/observability/NatsTracingUtil.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2220
=> Refactor code base

docs/spec/spec.md
fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2214
Fixes:
=> Add NATS specification

ballerina/tests/nats_basic_server_tests.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2510
=> Fix intermittent test failure

ballerina/tests/nats_basic_server_tests.bal
$title
fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2517
=> Add the intermittent test failure fix to all consumer service related test cases

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/NatsCompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_7/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_7/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/NatsServiceValidator.java
$title
fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2534
=> Fix compiler plugin crashing when there is a field variable in the service

ballerina/tests/nats_basic_server_tests.bal
Fixes intermittent test failures with isolated consumer services.
=> Fix nats intermittent test failures

ballerina/tests/nats_basic_server_tests.bal
**TESTING TEST FAILURES**
Doesn't reproduce locally. 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2586
=> Fix intermittent test failures

ballerina/Dependencies.toml, ballerina/tests/readonly_param_tests.bal, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/NatsCompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_17/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_17/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_8/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_8/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/NatsFunctionValidator.java, native/src/main/java/io/ballerina/stdlib/nats/Constants.java, native/src/main/java/io/ballerina/stdlib/nats/Utils.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java
- Add compiler plugin support for intersection types.
- Support intersection types in runtime impl.
Related to: 
https://github.com/ballerina-platform/ballerina-standard-library/issues/2611
https://github.com/ballerina-platform/ballerina-standard-library/issues/2612
=> Add support for intersection types

ballerina/client.bal, ballerina/listener.bal
related to:https://github.com/ballerina-platform/ballerina-standard-library/issues/2629
=> Add minor fixes to API docs

docs/spec/spec.md
=> Update introduction in spec.md

load-tests/simple_producer_consumer/scripts/load_test/main.bal, load-tests/simple_producer_consumer/src/main.bal
=> Increase load test time to 1hr

.github/workflows/trigger-load-tests.yml
=> Update load-test cluster name

ballerina/Dependencies.toml, ballerina/records.bal, ballerina/tests/data_binding_publish_tests.bal, ballerina/type_checker.bal, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/CodeSnippetGenerationCodeActionTest.java, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/NatsCompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_14/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_15/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_15/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_16/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_16/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/NatsFunctionValidator.java, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/PluginConstants.java, native/src/main/java/io/ballerina/stdlib/nats/Constants.java, native/src/main/java/io/ballerina/stdlib/nats/Utils.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2880
=> Add payload support to `onMessage` method

docs/proposals/data-binding.md, docs/spec/spec.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2817
=> Add data binding proposal & update spec

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/nats/Utils.java, native/src/main/java/io/ballerina/stdlib/nats/basic/client/Request.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java
$subject
Related to [`Update std libs with 2201.2.0 lang version #3128`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3128)
=> Migrate to update 2

ballerina/Ballerina.toml, gradle.properties
=> Update dependency versions

ballerina/Ballerina.toml, gradle.properties
=> Update lang version to 2201.2.0

ballerina/tests/constraint_tests.bal, ballerina/tests/nats_basic_server_tests.bal
related: https://github.com/ballerina-platform/ballerina-standard-library/issues/3401
**Merging this to load-test-results branch since this PR is failing, https://github.com/ballerina-platform/module-ballerinax-nats/pull/504**
=> Add client sharing for constraint tests

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, gradle.properties, native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/nats-native/reflect-config.json
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3409
- <s>[ ] Added tests</s>
- <s>[ ] Updated the spec</s>
=> Add native image build configurations

ballerina/tests/data_binding_publish_tests.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/server/docker-compose.yaml
An attempt to fix intermittent build failures. 
fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3638
- <s>[ ] Linked to an issue</s>
- <s>[ ] Updated the changelog</s>
- <s>[ ] Added tests</s>
- <s>[ ] Updated the spec</s>
- <s>[ ] Checked native-image compatibility</s>
=> Add a docker server for data binding tests

examples/build.gradle
=> Fix `bal build` to `bal test` for examples

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/nats/Utils.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/Detach.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Fix failing build for type reference support

gradle.properties
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3952
N/A
=> Update observe module version

ballerina/Dependencies.toml, ballerina/tests/constraint_tests.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/server/default-server.conf, ballerina/tests/server/docker-compose.yaml
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3957
=> Fix intermittently failing tests

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina-tests/build.gradle, ballerina-tests/tests/server/docker-compose.yaml, ballerina/Ballerina.toml, ballerina/build.gradle, ballerina/tests/constraint_tests.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/readonly_param_tests.bal, ballerina/tests/server/docker-compose.yaml
=> Fix test failures

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions for Update 5

native/src/main/java/io/ballerina/stdlib/nats/Utils.java
Partially fixes the issue https://github.com/ballerina-platform/ballerina-standard-library/issues/3933
=> Use convert API instead of `CloneWithType`

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, compiler-plugin-tests/build.gradle, gradle.properties
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4195
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4210
<s>- [ ] Updated the changelog</s>
<s>- [ ] Added tests</s>
<s>- [ ] Updated the spec</s>
<s>- [ ] Checked native-image compatibility</s>
=> Add code coverage for compiler plugin

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/jetstream_caller.bal, ballerina/jetstream_client.bal, ballerina/jetstream_records.bal, ballerina/records.bal, ballerina/tests/constraint_tests.bal, ballerina/tests/jetstream_client_tests.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/readonly_param_tests.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4362
=> Fix warnings in module build

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/jetstream_caller.bal, ballerina/jetstream_client.bal, ballerina/jetstream_records.bal, ballerina/records.bal, ballerina/tests/constraint_tests.bal, ballerina/tests/jetstream_client_tests.bal, ballerina/tests/nats_basic_server_tests.bal, ballerina/tests/readonly_param_tests.bal, gradle.properties
Fix warnings printed in module build
- <s>[ ] Linked to an issue</s>
- <s>[ ] Updated the changelog</s>
- <s>[ ] Added tests</s>
- <s>[ ] Updated the spec</s>
- <s>[ ] Checked native-image compatibility</s>
=> [2201.4.x] Fix warnings in module build

examples/order-manager/README.md
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4378
=> Update Meta Information in Examples

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update versions for Swan Lake U6

native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/DefaultMessageHandler.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/Detach.java, native/src/main/java/io/ballerina/stdlib/nats/basic/consumer/Register.java, native/src/main/java/io/ballerina/stdlib/nats/jetstream/listener/ListenerUtils.java, native/src/main/java/io/ballerina/stdlib/nats/jetstream/listener/StreamMessageHandler.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
=> Fix object getType() API usage

ballerina/type_checker.bal
=> Remove public keyword from TypeChecker

ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/Dependencies.toml
=> [Automated] Update the native jar versions

ballerina/Ballerina.toml, gradle.properties
=> Fix daily build failure

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, spotbugs-exclude.xml
=> Migrate to Java 17

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml
Update java version to 17.0.7
Fixes:
=> Update Java minor version

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Bump version to next minor version

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/CodeSnippetGenerationCodeActionTest.java, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/nats/plugin/NatsCompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_30/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/invalid_service_30/service.bal, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_23/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/valid_service_23/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/NatsServiceValidator.java, compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/PluginConstants.java, gradle.properties
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4733
=> [7.x] Update compiler plugin to allow annotations

ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update dependencies for u8

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
**Major version bump in:**  https://github.com/ballerina-platform/module-ballerinax-nats/pull/797. **Didn't mix the two.**
=> Update dependencies for U9

ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update versions for u9

ballerina-tests/Dependencies.toml, ballerina/Dependencies.toml, gradle.properties
=> Update versions for update 9

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/process-load-test-result.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml, .github/workflows/trivy-scan.yml
=> Update workflow template files

ballerina-tests/build.gradle, ballerina-tests/tests/server/compose.yaml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, ballerina/tests/server/compose.yaml
=> Update docker command to docker compose v2

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update library timestamp dependencies
